### ISSUE TITLE
Can't compile to ES5 using Babel

### ISSUE THREAD

**Issue by davegomez** [joakimbeng/unistyle#10]
I'm trying to compile my Unistyle module to ES5 using Babel for NPM distribution but I can't do it because Babel seems to have a problem with the spread operator I'm using to extend some properties.

Is there a way to do this?

This is the error log I am getting when try to compile:

```
> package@0.1.0 prepublish /Users/dave/Development/personal/package
> babel -d build src

ReferenceError: [BABEL] src/base-column.js: Unknown option: /Users/dave/Development/personal/package/.babelrc.stage
    at Logger.error (/Users/dave/.nvm/versions/node/v5.0.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/logger.js:43:11)
    at OptionManager.mergeOptions (/Users/dave/.nvm/versions/node/v5.0.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:18)
    at OptionManager.addConfig (/Users/dave/.nvm/versions/node/v5.0.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:205:10)
    at OptionManager.findConfigs (/Users/dave/.nvm/versions/node/v5.0.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:346:16)
    at OptionManager.init (/Users/dave/.nvm/versions/node/v5.0.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:391:12)
    at File.initOptions (/Users/dave/.nvm/versions/node/v5.0.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/Users/dave/.nvm/versions/node/v5.0.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/Users/dave/.nvm/versions/node/v5.0.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at transform (/Users/dave/.nvm/versions/node/v5.0.0/lib/node_modules/babel-cli/lib/babel/util.js:53:22)
    at Object.compile (/Users/dave/.nvm/versions/node/v5.0.0/lib/node_modules/babel-cli/lib/babel/util.js:62:12)

npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/dave/.nvm/versions/node/v5.0.0/bin/node" "/Users/dave/.nvm/versions/node/v5.0.0/bin/npm" "run-script" "prepublish"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.11
npm ERR! code ELIFECYCLE
npm ERR! package@0.1.0 prepublish: `babel -d build src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the package@0.1.0 prepublish script 'babel -d build src'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the package package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel -d build src
npm ERR! You can get their info via:
npm ERR!     npm owner ls package
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dave/Development/personal/package/npm-debug.log
```

**Comment by joakimbeng** [comment]
What Babel version are you using? If it's v6 you should probably install some [presets](https://babeljs.io/docs/plugins/) mainly [es2015](https://babeljs.io/docs/plugins/preset-es2015) and [stage-2](https://babeljs.io/docs/plugins/preset-stage-2) in your case. Then configure babel with:

``` json
{
  "presets": ["es2015", "stage-2"]
}
```

That should do the trick!

**Comment by davegomez** [comment]
This is already solved using the right Babel 6 configuration.
